flags: {}
packages:
  - '.'
  - location:
      git: https://github.com/expipiplus1/vulkan.git
      commit: c3006c1d913fc409340b99a6ecfbcb75a1b16296
    extra-dep: true
extra-deps:
- primitive-0.6.1.0
- vector-0.11.0.0
- vector-sized-0.3.2.0

resolver: ghc-8.0.1
